# Generated by Django 4.0.3 on 2022-03-09 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecurrencepattern',
            name='has_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskrecurrencepattern',
            name='has_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 2, 59, 0, 656057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventexception',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 2, 59, 0, 656057, tzinfo=utc)),
        ),
    ]
