# Generated by Django 4.0.3 on 2022-03-21 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_objectrecurrencepattern_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarobject',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='calendarobjectexception',
            name='start_date',
        ),
        migrations.AddField(
            model_name='calendarobject',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendarobjectexception',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
