# Generated by Django 4.0.3 on 2022-03-24 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_calendarobject_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarobject',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='calendarobjectexception',
            name='start_time',
        ),
        migrations.AddField(
            model_name='calendarobject',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendarobjectexception',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
