# Generated by Django 4.0.3 on 2022-04-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_calendarobject_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarobject',
            name='tz_offset',
            field=models.CharField(default='+00:00', max_length=6),
        ),
        migrations.AddField(
            model_name='calendarobjectexception',
            name='tz_offset',
            field=models.CharField(default='+00:00', max_length=6),
        ),
        migrations.AlterField(
            model_name='calendarobject',
            name='end_time',
            field=models.TimeField(default='17:14:03'),
        ),
        migrations.AlterField(
            model_name='calendarobject',
            name='start_time',
            field=models.TimeField(default='17:14:03'),
        ),
        migrations.AlterField(
            model_name='calendarobjectexception',
            name='end_time',
            field=models.TimeField(default='17:14:03'),
        ),
        migrations.AlterField(
            model_name='calendarobjectexception',
            name='start_time',
            field=models.TimeField(default='17:14:03'),
        ),
    ]
